version: '2'
services:
    jenkins.docker:
        image: shimmi/jenkins
        ports:
            - "8080:8080"
        volumes:
            - ./jenkins_home:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
        group_add:
            - docker